services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:${POSTGRES_PORT}"
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi_container
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    networks:
      - app-network

  test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    container_name: fastapi_test_container
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
