"""initial

Revision ID: 2b2c8c7efe81
Revises:
Create Date: 2024-11-14 02:22:26.470245

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b2c8c7efe81"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sources_url", table_name="sources")
    op.drop_table("sources")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("uid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("source_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "last_check_ts", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("is_publicated", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("uid", name="sources_pkey"),
    )
    op.create_index("ix_sources_url", "sources", ["url"], unique=True)
    # ### end Alembic commands ###
